##
# watchgo v1.0.0-alpha
#
# worker - maximum amount workers, Default value - 5
# verbose - verbose log, Default value - true
# worker_buffer - maximum buffer queue workers, Default value - 100
# event_buffer - maximum buffer an event reported by the underlying filesystem notification subsystem, Default value - 100
##
general:
  worker: 5
  worker_buffer: 100
  event_buffer: 300
  verbose: false
  info_log: './log/info.log'
  error_log: './log/error.log'
# paths - directories you need to track
# compress
# - enabled - compression image, if false image compress will not be processed
# - quality - This param image quality level in percentage.
# If the original image quality is lower than the quality of the parameter - quality the image will not be processed
# max_file_size -  maximum amount file size, default - 100. calculate 1 * 1024 megabyte
# - if zero value can unlimited size
# backup - location backup
#   - prefix of files to be processed, Default value all files - *
file_system:
  paths:
    - '/Users/hinha/Downloads'
  compress:
    enabled: true
    quality: 82
  max_file_size: 100
  backup:
#    hard_drive_path: "/Volumes/Hero"
    hard_drive_path: "/Users/hinha/Projects/test"
    prefix:
      - '*'
#      - '.gitignore'