name: Go

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19' ]

    env:
      GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      GO111MODULE: on
      MYAPP: watchgo

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: |
          mkdir -p build/amd64
          GOOS=linux GOARCH=amd64 go build -o build/amd64/${{ env.MYAPP }}-amd64 ./cmd/main.go