name: Go

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19' ]

    env:
      GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
      GO111MODULE: on

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Run build
        run: |
          mkdir -p build/{386,amd64}
          go mod vendor
          GOOS=linux GOARCH=386 go build -o build/386/${MYAPP}-386 ./watchgo-cloned/cmd/main.go
          GOOS=linux GOARCH=amd64 go build -o build/amd64/${MYAPP}-amd64 ./watchgo-cloned/cmd/main.go
