on:
  release:
    types: [created]
name: Build Release
jobs:
  release-matrix:
    name: release binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [ linux, darwin ]
        goarch: [ amd64 ]

    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: wangyoucao577/go-release-action@v1.32
        with:
          github_token: ${{ secrets.G_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          overwrite: true
          goversion: 1.19
          pre_command: export CGO_ENABLED=1
          build_command: go build
          project_path: "./cmd"
          binary_name: "watchgo"
          extra_files: LICENSE README.md
          md5sum: TRUE
          sha256sum: FALSE