on: release
name: Build Release
jobs:
  release-linux-amd64:
    name: release binaries linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: hinha/go-release.action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
          GOARCH: amd64
          GOOS: linux
          EXTRA_FILES: "LICENSE"
          CMD_PATH: ./cmd/main.go