name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        go: [ '1.19' ]
        goos: [ linux, darwin, windows ]
        goarch: [ amd64 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: wangyoucao577/go-release-action@v1.32
        with:
          github_token: ${{ secrets.G_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          overwrite: true
          goversion: ${{ matrix.go }}
          pre_command: export CGO_ENABLED=0
          ldflags: -X 'main.version=${{ github.event.release.tag_name }}' -X 'main.build=$(date)' -X main.docs=https://github.com/hinha/watchgo/blob/master/README.md
          build_command: go build
          project_path: "./cmd"
          binary_name: "watchgo"
          extra_files: LICENSE README.md
          md5sum: TRUE
          sha256sum: FALSE
          compress_assets: FALSE
